name: Test Task 1

on:
  push:
    branches: [ main ]
    paths:
      - 'task_1/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'task_1/**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      
      - run: cd task_1

      # Runs a single command using the runners shell
      - name: npm install
        run: npm install

      # Runs a set of commands using the runners shell
      - name: npm run test:coverage
        run: npm run test:coverage
