name: Test Task 3

on:
  push:
    branches: [main]
    paths:
      - "task_3/**"
  pull_request:
    branches: [main]
    paths:
      - "task_3/**"

jobs:
  Test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task_3

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - name: npm run test:coverage
        run: npm run test:coverage
